### ISSUE TITLE
Ettvdl not working....

### ISSUE THREAD

**Issue by Inside4ndroid** [SameerBidi/Torrent-Scraping#2]
Ettvdl is getting torrent list but returns error when trying to get torrent data... any chance of a quick fix :)

**Comment by SameerBidi** [comment]
I will check it in some time, thanks for reporting!

**Comment by SameerBidi** [comment]
Im so sorry im responding so late, i got into a job and completely forgot about this

i checked Ettv and the problem is not with the code but the Ettv domain not liking my proxy
I tried multiple different mirrors, none seem to work, all throw either a cloudflare error or straight 404 on the proxy that im using

So Ettvdl will stay down till i find a suitable proxy

**Comment by Inside4ndroid** [comment]
Okay thanks for responding :) hope you find a suitable proxy soon
